<template>
  <div class="viewer-container">
    
    <div 
      v-if="pdfUrl && activePage" 
      class="page-wrapper"
      :style="{ aspectRatio: `${activePage.width} / ${activePage.height}` }"
    >
      
      <VuePdfEmbed 
        :source="pdfUrl" 
        :page="activePage.page_number" 
        :text-layer="false"
        :annotation-layer="false"
        class="pdf-render-layer"
      />

      <div class="highlight-layer">
        <div
          v-for="(line, lineIndex) in activePage.elements"
          :key="lineIndex"
          class="highlight-box"
          :class="{ 'active': lineIndex === currentLineIndex }"
          :style="{
            left: `${(line.x / activePage.width) * 100}%`,
            top: `${(line.y / activePage.height) * 100}%`, 
            width: `${(line.width / activePage.width) * 100}%`,
            height: `${(line.height / activePage.height) * 100}%`
          }"
        ></div>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import VuePdfEmbed from 'vue-pdf-embed';
import { usePdfReader } from '../composables/usePdfReader';
import type { PdfPageData } from '../types/pdf';

const { pdfUrl, pdfPages, currentPageIndex, currentLineIndex } = usePdfReader();

const activePage = computed<PdfPageData | undefined>(() => {
  return pdfPages.value[currentPageIndex.value];
});
</script>

<style scoped>
.viewer-container { 
  flex: 1; 
  overflow-y: auto; 
  padding: 2rem; 
  display: flex; 
  justify-content: center; 
  background-color: #f0f0f0; 
}

.page-wrapper { 
  position: relative; 
  width: 100%;             
  max-width: 800px;        
  /* Removed height: fit-content; let aspect-ratio do the work */
  background: white; 
  box-shadow: 0 4px 8px rgba(0,0,0,0.2); 
}

/* THE FIX: Force the PDF wrapper AND its internal canvas to absolutely fill our rigid box */
.pdf-render-layer { 
  position: absolute;
  top: 0;
  left: 0;
  width: 100%; 
  height: 100%;
}

/* Target the internal canvas generated by vue-pdf-embed to stretch perfectly */
:deep(.vue-pdf-embed canvas) {
  width: 100% !important;
  height: 100% !important;
  display: block; /* Kills the phantom margin entirely */
}

.highlight-layer { 
  position: absolute; 
  top: 0; 
  left: 0; 
  width: 100%; 
  height: 100%; 
  pointer-events: none; 
}

.highlight-box { 
  position: absolute; 
  background-color: transparent; 
  border-radius: 2px; 
  transition: background-color 0.1s; 
}

.highlight-box.active { 
  background-color: rgba(255, 215, 0, 0.4); 
  box-shadow: 0 0 4px rgba(255, 215, 0, 0.8); 
}
</style>